---
- name: Backup the master nodes
  hosts: masters
  become: true
  roles:
    - backup_masters

- name: Backup all the nodes
  hosts: nodes
  become: true
  roles:
    - backup_nodes

- name: Update the software repositories
  hosts: nodes
  become: true
  roles:
    - software_repositories
