---
- name: Load the cluster
  hosts: localhost
  roles:
    - load_cluster

- name: Install openshift-ansible on the localhost
  hosts: localhost
  become: true
  roles:
    - install_configure

- name: Backup the master nodes
  hosts: masters
  become: true
  roles:
    - backup_masters

- name: Backup all the nodes
  hosts: nodes
  become: true
  roles:
    - backup_nodes

- name: Update the software repositories
  hosts: all
  become: true
  roles:
    - software_repositories

- name: Perform the upgrade
  hosts: localhost
  roles:
    - upgrade_openshift
