---
- name: Install openshift-ansible from the package manager
  package:
    name: "openshift-ansible"
    state: latest

- name: Copy the ansible.cfg from openshift-ansible
  copy:
    backup: yes
    dest: /etc/ansible/ansible.cfg
    remote_src: yes
    src: /usr/share/ansible/openshift-ansible/ansible.cfg

- name: Edit the inventory file
  replace:
    backup: yes
    path: "{{ inventory_path }}"
    regexp: "ansible_ssh_private_key_file=\".*?\""
    replace: ""

- name: Reload the inventory file
  meta: refresh_inventory
