---
- name: Print out the node status
  shell: oc get nodes -o wide | tee before_cluster_load_nodes.txt

- name: Print out the current projects
  shell: oc get projects --all-namespaces | tee before_cluster_load_projects.txt

- name: Print out the current pods
  shell: oc get pods --all-namespaces | tee before_cluster_load_pods.txt

- name: Set the KUBECONFIG environment variable
  set_fact:
    kubeconfig: "export KUBECONFIG={{ ansible_user_dir }}/.kube/config"

- name: Pause to verify the cluster loader configuration
  pause:
    prompt: "About to load {{ cluster_loader_configuration }}. Continue?"

- name: Run the Cluster loader program
  shell: >
    {{ kubeconfig }}
    /usr/libexec/atomic-openshift/extended.test --ginkgo.focus="Load cluster"
    --viper-config={{ cluster_loader_configuration }} 2>&1 | tee {{ ansible_user_dir }}/load_cluster.log
  args:
    chdir: "{{ cluster_loader_base_directory }}"
    executable: /bin/bash

- name: Print out the node status
  shell: oc get nodes -o wide | tee after_cluster_load_nodes.txt

- name: Print out the current projects
  shell: oc get projects --all-namespaces | tee after_cluster_load_projects.txt

- name: Print out the current pods
  shell: oc get pods --all-namespaces | tee after_cluster_load_pods.txt
