---
- name: Pause before running upgrade
  pause:
    prompt: "About to run the upgrade to {{ openshift_version_end }}. Continue?"
    seconds: 10

- name: Copy the inventory file
  copy:
    src: "{{ inventory_path }}"
    dest: "{{ inventory_path }}"

- name: Perform the upgrade
  shell: >
    ansible-playbook -vvv
    -i {{ inventory_path }}
    /usr/share/ansible/openshift-ansible/playbooks/byo/openshift-cluster/upgrades/v{{ openshift_version_end | regex_replace('\.', '_') }}/upgrade.yml 2>&1 > upgrade.log
  args:
    # Use bash to get the posix style redirects.
    executable: /bin/bash

- name: Pause to give pods more time to start
  pause:
    seconds: 5

- name: Print out the node status after upgrade
  shell: oc get nodes -o wide | tee upgraded_nodes.txt

- name: Print out the current projects after upgrade
  shell: oc get projects --all-namespaces | tee upgraded_projects.txt

- name: Print out the current pods after upgrade
  shell: oc get pods --all-namespaces | tee upgraded_pods.txt
