---
- name: Edit the inventory file before the upgrade
  replace:
    backup: yes
    path: "{{ inventory_path }}"
    regexp: 'ansible_ssh_private_key_file=".*?"'
    replace: 'ansible_ssh_private_key_file="{{ ansible_ssh_private_key_file }}"'

- name: Reload the inventory file after making changes
  meta: refresh_inventory

- name: Download the cluster data
  get_url:
    url: "{{ cluster_data_url }}"
    dest: "{{ cluster_data_url | basename }}"
  when: cluster_data_url != ""
